import { Inter } from 'next/font/google'
import './globals.css'
import ServiceWorkerRegistration from './ServiceWorkerRegistration' // <-- स्टेप 1: इम्पोर्ट करें

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create.xyz App',
  description: 'Generated by create.xyz',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ServiceWorkerRegistration /> {/* <-- स्टेप 2: यहाँ डालें */}
        {children}
      </body>
    </html>
  )
}
